name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9
            runs-on: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Python 3.8
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: py38

          - name: Python 3.7
            runs-on: ubuntu-latest
            python-version: 3.7
            toxenv: py37

          - name: Python 3.6
            runs-on: ubuntu-latest
            python-version: 3.6
            toxenv: py36

          - name: Coverage
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: coverage

          - name: Black
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: black

          - name: Flake8
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: flake8

          - name: Bandit security audit
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: bandit
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
